server:
  port: 8081
spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://47.104.20.179:3306/yc?allowMultiQueries=true&useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: select 1
      validation-query-timeout: 2000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat,wall
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        allow: 0.0.0.0
        login-username: yzm
        login-password: 123
  jackson:
    default-property-inclusion: non_null
  redis:
    port: 6379
    host: 47.104.20.179
    password: 135790
    database: 0
    jedis:
      pool:
        max-active: 1000
        max-idle: 100
        max-wait: 1ms
        min-idle: 5
  activemq:
    broker-url: tcp://47.104.20.179:61616
    user: admin
    password: admin
    in-memory: false
    queue-name: active.queue
    topic-name: active.topic.name.model
  application:
    name: service-admin
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix: yc_
  mapper-locations: classpath:/mapper/*/*.xml
logging:
  level:
    com.yzm: debug
    org.springframework: info