spring:
  application:
    name: zm-gateway
  # 开启 Gateway 服务注册中心服务发现
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: a
          uri: http://localhost:8080/user/list
          predicates:
            - Path=/user/**
# Eureka Server 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
# 配置Gateway日志等级，输出转发细节信息
logging:
  level:
    org.springframework.cloud.gateway: debug
server:
  port: 8081
